export enum AppVariables {
  SERVER_PORT = "SERVER_PORT",
  MONGO_URI = "MONGO_URI",
  MONGO_DB_NAME = "MONGO_DB_NAME",
  CACHE_TIMEOUT = "CACHE_TIMEOUT",
  SPREADSHEET_ID = "SPREADSHEET_ID",
  SPREADSHEET_URL = "SPREADSHEET_URL",
  SPREADSHEET_API_KEY = "SPREADSHEET_API_KEY",
  SPREADSHEET_RANGE_NAME = "SPREADSHEET_RANGE_NAME",
}
